### ISSUE TITLE
implement add new article (backend)

### ISSUE THREAD

**Issue by ringaile** [ringaile/honest_media#11]
To make it simple on frontend,

we can have just few text fields:
author address
title
link to the article
and button add
etc

and it is added to the list of articles

also, once the article is added, it should updated the list of published articles:
related to  #8

**Comment by ajmachado** [comment]
See my comments about metadata storage in [#8](https://github.com/ringaile/honest_media/issues/8)

**Comment by ringaile** [comment]
not yet, I think ipfs will be a new issue separated from this one, because it is a big issue.
lets have main functionality implemented by the end of this week and then focus on such tasks. what do you think?

**Comment by ajmachado** [comment]
I am moving the frontend to a new issue.

**Comment by ringaile** [comment]
we can close it, right?

**Comment by ajmachado** [comment]
In app.js, only the 'updateContributorRating' rating is called. The 'upVoteArticle' needs to be called as well to register the vote.
