### ISSUE TITLE
implement add new article (frontend)

### ISSUE THREAD

**Issue by ajmachado** [ringaile/honest_media#14]

**Comment by ajmachado** [comment]
Can I close this one, since we have a new one for IPFS?

**Comment by ajmachado** [comment]
[#26](https://github.com/ringaile/honest_media/pull/26)

**Comment by ringaile** [comment]
yes, we can close it

**Comment by ajmachado** [comment]
Implemented in PR [#26](https://github.com/ringaile/honest_media/pull/26)
