### ISSUE TITLE
Implement approve article (frontend)

### ISSUE THREAD

**Issue by ajmachado** [ringaile/honest_media#17]

**Comment by ajmachado** [comment]
How should we implement this?

**Comment by ringaile** [comment]
that means, if the contributor submits the article, it should be approved before it is published (appears on a list), right? And it should be also proved by validators or fellow contributors?

So then we will have two features to ensure that article is correct (approve the article and challenge the article). On one had, it is good to have it, but also maybe it is redundant? 
I think we can implement it if we have time, but it is a good idea

**Comment by ajmachado** [comment]
If the validator approves it, do we need fellow contributors to approve it as well? Or maybe we can change this to allow only fellow contributors to approve a new article and the validator can only rule on challenges. What do you think? I will hold off on merging the PR for the approve backend

**Comment by ringaile** [comment]
_Or maybe we can change this to allow only fellow contributors to approve a new article and the validator can only rule on challenges._ 

I like this idea but i also wonder, if fellow contributors might not approve the article on purpose just because they are jealous or do not like the contributor, and not because the article is fake.

**Comment by ajmachado** [comment]
Good thinking :) Should we just keep it simple and let the validator approve the articles?

**Comment by ringaile** [comment]
yes, i think so

**Comment by ajmachado** [comment]
Ok. I'll merge the PR for the backend. 
How should the frontend look? Have a validators section with a list of articles awaiting approvals and an 'Approve' button?

**Comment by ringaile** [comment]
yes,i think we should have a list of articles and each article has an approve button :)
