### ISSUE TITLE
calculate rating for reader

### ISSUE THREAD

**Issue by ringaile** [ringaile/honest_media#23]

**Comment by ringaile** [comment]
Let’s keep it simple. 
If we keep rating from 1 to 100

So we present the percentage of a ratio of correctly challenged articles / all challenged articles. 

That means, if a reader challenged 5 articles and all the articles were fake. It means he spotted the fake ones and his rating is 5/5*100 = 100 

If the reader challenged 5 articles, but it turned out that 2 of them were correct it means, he found only 3 fake articles and his rating is 
3/5*100= 60 
And so on

What do you think?

**Comment by ajmachado** [comment]
What should we rate readers who have not challenged any articles?

**Comment by ringaile** [comment]
0 rating to keep it simple

**Comment by ajmachado** [comment]
Ok. So, basically similar to the contributor rating calculator. We are doing a 0 to 5 rating for contributors. Should we do the same for readers as well?

**Comment by ringaile** [comment]
i think yes

**Comment by ajmachado** [comment]
Ok. I'll take care this, unless you want it :)

**Comment by ringaile** [comment]
you can take, i currently work on two issues
