### ISSUE TITLE
calculate rating for validator

### ISSUE THREAD

**Issue by ringaile** [ringaile/honest_media#24]

**Comment by ringaile** [comment]
validator just validates the articles. 
And maybe his ranking can be based only the number of articles validated? The more articles he validated, the better ranking he has?

**Comment by ajmachado** [comment]
Validator also rules on challenges. But for both approve and ruling challenges the validator is chosen randomly.

**Comment by ajmachado** [comment]
How about this: The validator will lose ranking if an article he approves loses the challenge. And vice versa. In this case, we may want to think of assigning all Validators a starting rank of 2 or 3.

What do you think?

**Comment by ringaile** [comment]
i think it could work, we can take a lower one, 2
