### ISSUE TITLE
readme

### ISSUE THREAD

**Issue by ringaile** [ringaile/honest_media#34]
i started working on readme:
https://github.com/ringaile/honest_media/tree/readme

**Comment by ajmachado** [comment]
What part of the documentation would you like me to work on?

**Comment by ringaile** [comment]
I saw in the document that You wrote:
_Fake news in India has even resulted in mob beatings and harassments where some people have lost their lives._

Maybe You can write it as our use case for the app?

**Comment by ringaile** [comment]
PR created

**Comment by ajmachado** [comment]
There is a typo at "Feature App Features" it should be "Future App Features"

**Comment by ringaile** [comment]
fixed.
