### ISSUE TITLE
implement article role

### ISSUE THREAD

**Issue by ringaile** [ringaile/honest_media#5]

**Comment by ajmachado** [comment]
Does the article need an address? Also, only a contributor will be able to add an article. Will that check happen in the main contract?

**Comment by ringaile** [comment]
i think, you are right, the article does not need an address. maybe it is enough to have an array or mapping of article structs in contributor's role.
and yes, the check should probably happen in main contract

**Comment by ajmachado** [comment]
I have added the article array to the contributor struct. Take a look

**Comment by ringaile** [comment]
we can already close this issue, right?

**Comment by ajmachado** [comment]
Yes. I think we can close it.
