### ISSUE TITLE
implement  update rating 

### ISSUE THREAD

**Issue by ringaile** [ringaile/honest_media#7]
at the moment we have only setrating function for contributors.
But we want to update rating after each article like or so.

we need to create some algorithm to calculate rating.

So far, we have a contributor with many articles and each has likes/dislikes.

we have to decide how much each like/dislike is valued and how we calculate it

**Comment by ajmachado** [comment]
_at the moment we have only setrating function for contributors.
But we want to update rating after each article like or so._
We can use the same function to update rating. We are just overwriting the value.

**Probable Simple Rating/Reputation calculation example: for Contributors** 
Rating range 0 - 100 (which can be converted to 0-5)
Current rating: 50 (10 previous articles published)
New Article: Up votes 50      down votes 25
Rating for new article = 50/75 * 100 = 67 approx.
New Rating = (10 * 50 + 67) / 11 = 51 approx
Successful challenge: lose a fixed number of points

Also, we need to decide if we should allow the votes for the life of the article or just a fixed period after it has been published.

**Comment by ringaile** [comment]
Ok for the rating. 
As I mentioned before, let’s keep all time constrains for future :)

**Comment by ajmachado** [comment]
I have added the function to calculate the rating for contributors as described above. I wasn't sure how we would calculate the rating for validators and readers.

**Comment by ringaile** [comment]
created PR

**Comment by ajmachado** [comment]
We can close this
