### ISSUE TITLE
display all article titles with links as a list (frontend)

### ISSUE THREAD

**Issue by ringaile** [ringaile/honest_media#8]
also, backend if needed

**Comment by ajmachado** [comment]
Yes. We can display all articles in order they are published. Have you given any thought on how we can store the article metadata off chain? Should we store it in a csv file which we can upload to IPFS?

**Comment by ringaile** [comment]
Let’s say this story doesn’t include ifps yet cause it would be too big. 
Let’s implement just simple display/implementation of article struct. 
And next story will be only about ifps :)

**Comment by ajmachado** [comment]
Will the article metadata ex: Title & Date be stored on the chain in the article struct?

**Comment by ringaile** [comment]
I’m ok without storing it on chain.
